### ISSUE TITLE
iOS Safari double-clicking causes the page to be enlarged and unavailable

### ISSUE THREAD

**Issue by haolloyin** [himitsuconfidential/downstack-practice#4]
Hi dev, this is a very good Tetris training tool. 

But when I practice on iPhone X's Safari browser, if I double click the screen (button) a little faster, the whole page will be enlarged.

I've tried other normal web pages and this problem doesn't happen, can you please fix this problem? Thanks.

**Comment by himitsuconfidential** [comment]
Thank you for raising this issue. 
I will fix this issue later.
I will reply you when this issue is fixed

**Comment by himitsuconfidential** [comment]
The problem is fixed, try it

**Comment by haolloyin** [comment]
@himitsuconfidential 
Here is my new testing process and results, I closed the page, killed Safari, and re-entered the URL to test:

- [x] Double click anywhere but the button, works fine, page does not enlarge.

- [x] Quickly clicking on multiple different buttons, works fine.

- [ ] Double click on the same button (within the rectangle), **_the page will be enlarged,_** then double click anywhere will make the page return to normal size.
